APP_OUTPUT = {'en':{
  'INCORRECT_COMMAND': '"Unknown command. "', 
  'INCORRECT_REQUIRED_PARAMS': '"Required parameter is missing. Usage: {0} {1} {2}. "', 
  'INCORRECT_CONDITIONAL_PARAMS': '"Parameter {0} with value \'{1}\' requires parameter {2} with correct value. "', 
  'EMPTY_PARAM_VALUE': '"Parameter {0} can not be empty. "', 
  'INCORRECT_PARAMS': '"Invalid syntax. It must be either --<param_name>=<param_value> or -<short_param_name> <param_value>. "', 
  'UNREGISTERED_COMP': '"This server is not registered in SqlBak.com. You can do it by running sqlbak -r -k <your_secret_key> -n <your_computer_name>. "', 
  'COMP_CONNECTED': '"This server is already registered in SqlBak.com (account {0}) as {1}. To unbind the application from sqlbak.com run: {2} --unregister"', 
  'SUCCESSFUL_CONNECTED': '"{0} has been successfully registered in SqlBak.com (account {1}). "', 
  'DOUBLE_CONNECTION': '"The connection already exists. Run --update-connection to change the connection to DBMS. For more information execute: {0} --help ---command=update-connection"', 
  'CONNECTION_ADDED': '"The connection has been successfully added. "', 
  'CONNECTION_NOT_FOUND': '"The connection with id={0} is not found. "', 
  'CONNECTION_UPDATED': '"The connection has been successfully updated. "', 
  'NO_CONNECTIONS': '"There are no connections {0} yet. "', 
  'NO_ANY_CONNECTIONS': '"There are no connections. "', 
  'TEST_CONNECTION_SUCCESS': '"\\nThe connection is tested successfully. "', 
  'TEST_CONNECTION_FAILED': '"\\nThe connection test failed: {0}. "', 
  'DELETE_CONNECTION_FAILED': '"Can not delete the connection since it is used in {0} job(s). "', 
  'CONNECTION_DELETED': '"The connection has been successfully removed. "', 
  'NO_JOBS': '"There are no jobs yet. "', 
  'CONNECTION_NOT_CHANGED': '"The connection settings have not changed. "', 
  'WRONG_SERVER_TYPE': '"{0} is a wrong DBMS type. The possible values are: {1}. "', 
  'COMP_NAME_UNCHANGED': '"The server name has not changed ({0}). "', 
  'UTILS_PATH_CHANGED': '"The сurrent paths to DBMS are: {0}. "', 
  'SAVE_AGENT_NAME_FAILED': '"Failed to send connection details to SqlBak.com: {0}. "', 
  'EMPTY_MESSAGE_HANDLER': '"Failed to get command\'s handler {0} {1}. "', 
  'FAILED_HANDLE_COMMAND': '"Handling a console command has failed. {0}. "', 
  'NEW_CLIENT_NAME': '"The name of this server is set to {0}. "', 
  'HELP_PARTIAL': '"\\nTo get details for a specific command type:\\n  sqlbak --help <-h> --command <-c> <command_name_without_dashes>. "', 
  'CURRENT_CLIENT_VERSION': '"SqlBak application {0}\\nCopyright (c) {1} Pranas.NET. "', 
  'LOGS_UPLOADED': '"The logs have been successfully uploaded. "', 
  'LOGGING_STATUS': '"The logging is {0}. "', 
  'CLIENT_INFO': '"Server name: {0}\\nSqlBak.com account: {1}\\nStatus: the server is {2} in SqlBak.com\\nLogging: the logging is {3}. "', 
  'ROOT_PERMISSION': '"Permission error. You should execute SqlBak app with root privileges. "', 
  'FAILED_GET_CLIENT_INFO': '\'Failed to get the information. "{0}". \'', 
  'FAILED_ACTIVATE_LOGS': '\'Failed to activate the logging. "{0}". \'', 
  'FAILED_UPLOAD_LOGS': '\'Failed to upload the logs to SqlBak.com. "{0}". \'', 
  'FAILED_SHOW_COMMANDS': '\'Failed to show a list of console commands. "{0}". \'', 
  'FAILED_RUN_JOB': '\'Failed to run the job. "{0}". \'', 
  'FAILED_GET_JOBS': '\'Failed to get the list of jobs. "{0}". \'', 
  'FAILED_REMOVE_CONNECTION': '\'Failed to remove the connection. "{0}". \'', 
  'FAILED_REMOVE_JOB_CRED': '\'Failed to remove the job credential from SqlBak.com: "{0}". \'', 
  'FAILED_TEST_CONNECTION': '\'Failed to test DBMS connection. "{0}". \'', 
  'FAILED_GET_CONNECTION': '\'Failed to get DBMS connection. "{0}". \'', 
  'FAILED_GET_CONNECTIONS': '\'Failed to get DBMS connections. "{0}". \'', 
  'FAILED_UPDATE_CONNECTION': '\'Failed to update DBMS connection. "{0}". \'', 
  'FAILED_ADD_CONNECTION': '\'Failed to add DBMS connection. "{0}". \'', 
  'FAILED_DEACTIVATE_CLIENT': '\'Failed to unregister the server. "{0}". \'', 
  'FAILED_UPDATE_PATHS': '\'Failed to update DBMS paths. "{0}". \'', 
  'FAILED_UPDATE_CLIENT': '\'Failed to update the settings. "{0}". \'', 
  'FAILED_REG_CLIENT': '\'Failed to register this server. "{0}". \'', 
  'FAILED_UPDATE_NAME': '\'Failed to update server\\\'s name. "{0}". \'', 
  'FAILED_ACTIVATE_CLIENT': '\'Failed to reregister this server. "{0}". \'', 
  'FAILED_GET_VERSION': '"Failed to get application version. "', 
  'FAILED_URL': '"URL for uploading was not received. "', 
  'PARTIAL_UPLOAD': '"Partial uploading. "', 
  'FAILED_CONNECT_DROPBOX': '"Failed to connect to DropBox. Looks like an access token hasn\'t been added. "', 
  'FAILED_UPLOAD_DROPBOX': '\'Failed to upload a file to DropBox. "{0}"\'', 
  'FAILED_RECEIVE_MESSAGES': '\'Messages have not been received. "{0}". \'', 
  'NO_MESSAGE_HANDLER': '"A message does not have a handler. "', 
  'FAILED_TEST_DEST': '\'Failed to test the destination. "{0}". \'', 
  'FAILED_UPGRADE_APP': '\'Failed to upgrade the application. "{0}". \'', 
  'FAILED_CHECK_TEMP_FOLDER': '"Failed to check a temporary folder. The path does not exist. "', 
  'NO_BACKUPS': '"There are no backups. "', 
  'FAILED_RESTORE_BACKUP': '\'Failed to restore a backup. "{0}". \'', 
  'FAILED_DOWNLOAD_BACKUP': '\'Failed to download a backup. "{0}". \'', 
  'FAILED_GET_DBMS_SETTS': '"Failed to get DBMS settings. "', 
  'FAILED_GET_BACKUP_OBJECT': '\'Failed to get a backup object. "{0}". \'', 
  'FAILED_GET_DEST_SETTS': '"Failed to get a destination settings"', 
  'BACKUP_EMPTY': '"An uncompressed backup folder is empty. "', 
  'FAILED_TRACE_RESTORE': '\'Failed to trace the restoration. "{0}". \'', 
  'FILE_NOT_EXISTS_DEST': '"A backup file {0} doesn\'t exist at the destination. "', 
  'FAILED_CANCEL_DOWNLOAD': '\'Failed to cancel the downloading. "{0}". \'', 
  'BACKUP_NOT_FOUND': '\'Backup was not found by a remote id - "{0}". \'', 
  'CANCEL_JOB': '"The job is canceled by a user. "', 
  'FAILED_RUN_TRIGGER': '"The backup is not found. "', 
  'FAILED_RUN_SCRIPT_BEFORE_BACKUP': '\'Failed to run a script before the backup. "{0}". \'', 
  'FAILED_RUN_SCRIPT_AFTER_BACKUP': '\'Failed to run a script after the backup. "{0}". \'', 
  'FAILED_VERIFY_FILE': '\'Failed to verify if a file "{0}" exists. "{1}". \'', 
  'FAILED_CREATE_FOLDER_BACKUP': '\'Failed to create a folder backup. "{0}". \'', 
  'FAILED_DELETE_OVERDUE_BACKUP': '\'Failed to delete an overdue backup. "{0}". \'', 
  'FAILED_CLEAN_OVERDUE_BACKUP': '\'Failed to cleanup overdue backups. "{0}". \'', 
  'FILE_NOT_EXISTS': '\'A resource "{0}" doesn\\\'t exist. \'', 
  'FAILED_TRACE_BACKUP_OBJECT': '\'Failed to trace a backup object result. "{0}". \'', 
  'FAILED_SEND_OBJECTS': '\'Failed to send a backup object to SqlBak.com. "{0}". \'', 
  'APP_VERSION_ACTUAL': '"The current version of the application is up to date. "', 
  'FAILED_GET_UPDATE_STATUS': '\'Failed to get application update status "{0}". \'', 
  'CANNOT_UPDATE_APP': '"The application can not be updated now "', 
  'INCORRECT_JOB_TYPE': '\'A job type is incorrect - "{0}". \'', 
  'INVALID_JOB': '\'A job with id "{0}" does not exist. \'', 
  'FAILED_CHECK_JOB_RUN': '\'Failed to check if a job is running. "{0}". \'', 
  'TIMEOUT': '"Timeout exception! "', 
  'EXTRA_FILE_SIZE': '"The file size is too large. "', 
  'INVALID_PATH_TYPE': '"Failed to get a correct path. Path {0} is not a string. "', 
  'FAILED_GET_FREE_SPACE': '\'Failed to get free disk space data. "{0}". \'', 
  'FAILED_SET_JOB_SETTINGS': '\'Failed to set job settings. "{0}". \'', 
  'FAILED_CHECK_VIOLATION': '\'Failed to check a plan violation. "{0}". \'', 
  'INVALID_FILE_SIZE': '"File size can not be less than zero. "', 
  'FAILED_BACKUP_DBMS': '\'Failed to backup a DBMS - "{0}" . "{1}". \'', 
  'FAILED_CREATE_DBMS': '\'Failed to create a new DBMS "{0}" - "{1}". \'', 
  'FAILED_RESTORE_DBMS': '\'Failed to restore a DBMS - "{0}". "{1}". \'', 
  'FAILED_DIFF_RESTORE': '\'Failed to restore a differential backup - "{0}". "{1}". \'', 
  'FAILED_TRANS_RESTORE': '\'Failed to restore a transaction log backup - "{0}". "{1}". \'', 
  'INVALID_DESTINATIONS': '"Failed to send a compressed backup. There are no correct destinations. "', 
  'INVALID_BACKUP_TYPE': '\'An invalid backup type is received. "{0}". \'', 
  'FAILED_SEND_BACKUP': '\'Failed to send a compressed backup to a destination - "{0}". "{1}". \'', 
  'FAILED_UPDATE_OBJECT': '"Failed to update object backup results. {0}. "', 
  'FAILED_TRIGGER_BACKUP_TYPE': '\'Failed to get a backup type for a trigger - "{0}". \'', 
  'INTERRUPTED_JOB': '"[JOB:1001] The backup job was unexpectedly interrupted. "', 
  'BROKEN_CHAIN': '"A backup chain is broken. "', 
  'FAILED_UPDATE_DOWN_ALERT_INTERVAL': '\'Failed to update down alert notification interval. "{0}". \'', 
  'FAILED_TEST_CONNECTION_STATE': '\'Failed to check a DBMS connection\\\'s state. "{0}". \'', 
  'FAILED_GET_DBMS_TYPE_BY_NAME': '"Failed to get DBMS type by a name and a connection type. "', 
  'INCORRECT_PLAN_WITHOUT_NAME': '\'Your account is temporarily suspended. Please check your account at "{0}" website. \'', 
  'INCORRECT_PLAN_WITH_NAME': '\'Your account with "{0}" plan is temporarily suspended. Please check your account at "{1}" website. \'', 
  'SERVER_COUNT_EXCESS': '\'Your plan is limited to "{1}" server(s). You currently have "{0}". Please remove extra servers (on the servers page). \'', 
  'DATABASE_COUNT_EXCESS': '\'Your plan is limited to "{1}" databases. You currently backup "{0}" databases. Please remove extra databases from your backup jobs. \'', 
  'FEATURE_EXCESS': '\'"{0}" feature is not available in your current plan. Please change the configuration. \'', 
  'DESTINATION_NOT_ALLOWED': '\'"{0}" destination ("{1}") is not available in your current plan. Please remove the destination. \'', 
  'DESTINATION_FEATURE_NOT_ALLOWED': '\'"{0}" feature of "{1}" destination ("{2}") is not available in your current plan. Please change the configuration. \'', 
  'INVALID_VIOLATION_PLAN': '\'Some backup features you use exceed the limitations of your current plan. Please upgrade or make the following changes: "{0}". \'', 
  'FAILED_VERIFY_AFTER_BACKUP': '\'Failed to verify a backup. "{0}". \'', 
  'FAILED_DB_OFFLINE': '\'Failed to check if a database "{0}" is offline. "{1}". \'', 
  'DB_OFFLINE': '\'Database "{0}" is offline and an "Ignore Offline databases" option is not enabled. \'', 
  'FAILED_GET_ONE_DRIVE_ITEM': '\'Failed to get an OneDrive item - "{0}". \'', 
  'ABSENT_DATABASES_AND_FOLDERS': '"Databases and folders are not selected. "', 
  'CREATE_DBMS_CONNECTION_1': '"\\nNow you need to add a connection to DBMS (MySQL, PostgreSQL, MSSQL Server). Run:\\n{0} -ac -dt <dbms_type> -h <host> -u <user_name> -p <password>\\n"', 
  'CREATE_DBMS_CONNECTION_2': '"For example:\\nMySQL: {0} -ac -dt mysql -h <host> -u <user> -p <user_password>\\nPostgreSQL: {0} -ac -dt postgresql -h <host> -u <user> -p <user_password>\\nMS SQL SERVER: {0} -ac -dt mssql -h <host> -u <user> -p <user_password>\\nMongoDB: {0} -ac -dt mongo -h <host> -u <user> -p <user_password>\\n"', 
  'CREATE_DBMS_CONNECTION_3': '"To find more details use: {0} -h -c ac\\n"', 
  'DESTINATION_IS_ABSENT': '\'Destination "{0}" is absent locally. \'', 
  'FAILED_RESTORE_TRIGGER': '\'Failed to restore the backup "{0}". "{1}"\'', 
  'AUTO_UPDATE_DISABLED': '"Automatic updates of SqlBak app are disabled"', 
  'FAILED_SET_AGENT_ACTIVITY': '\'Failed to set the server activity. "{0}"\'', 
  'ABSENT_DOWNLOAD_PACKAGE': '"The download package is not exist"', 
  'UNSUPPORTED_DISTRO': '\'The Linux distribution ("{0}") version is not supported\'', 
  'MISSED_DBMS_UTIL': '\'"{0}" utility is not found. The default path to "{0}" utility is "{1}". If your path is different you can change it like: {3} --update-settings --{2}=</path/to/utility> If the utility is not installed yet, please install it.\'', 
  'MISSED_SQLPACKAGE_UTIL': '"To backup the Azure database, sqlpackage utility is required \\nsqlpackage utility cannot be found at the following path {0}\\n\\nInstall sqlpackage utility and specify a path to it via the following command:\\nsudo sqlbak --update-settings --sqlpackage-path=</path/to/sqlpackage>\\n\\nMore information about sqlpackage at:\\nhttps://docs.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-download"', 
  'MISSED_SQLCMD_UTIL': '"To backup the Azure database, sqlcmd utility is requiredsqlcmd utility cannot be found at the following path {0}Install sqlpackage utility and specify a path to it via the following command:sudo sqlbak --update-settings --sqlcmd-path=</path/to/sqlcmd>More information about sqlpackage at:https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-tools"', 
  'FAILED_FINGERPRINT': '"Fingerprint from the server is not equal the fingerprint in destination settings"', 
  'ROW_FORMAT_DISABLED': '"Error enabling binary logs. ROW format for the binary log is not enabled. Please execute the following command: {1} --configure-mysql --connection-id={0} to enable binary log via SqlBak, or you can do it manually. "', 
  'BIN_LOG_DISABLED': '"Error enabling binary logs. The binary log is not enabled. Please execute the following command: {1} --configure-mysql --connection-id={0} to enable binary log via SqlBak, or you can do it manually. "', 
  'LOG_SLAVE_UPDATES_DISABLED': '"Your MySQL database is part of a Galera cluster. However, it is configured in such a way that transactions executed on other MySQL instances are not being recorded in this instance\'s binary logs. Please add \'log_slave_updates=1\' to the [mysqld] section of your my.cnf. After making this change, remember to restart your MySQL service."', 
  'FAILED_GET_LIB_DIR_MYSQL': '"Error enabling binary logs. Failed to get a path to the MySQL lib directory. "', 
  'MSSQL_GET_DB_DATA_FAILED': '"Failed to get database data. Empty output"', 
  'BACKUP_FAILED_NO_RESTORE': '"The backup failed and cannot be restored."', 
  'FAILED_CHECK_IF_SERVER_DELETED': '"Failed to check if the server is deleted. {0}"', 
  'WRONG_BIN_LOG_PARAMS': '"\\nTo correctly perform incremental backups via SqlBak, you need to adjust the binary log settings.\\n\\nRecommended binlog parameters are:\\n\\nserver-id = 1\\nlog_bin = /var/log/mysql/mysql-bin.log\\nmax_binlog_size = 100M\\nbinlog_format=ROW\\n\\nPlease adjust these parameters in the file /etc/mysql/my.cnf"', 
  'ACTIVATE_BIN_LOGS': '"\\nTo activate binlog files, you need to set your MySQL Server configuration file /etc/mysql/my.cnf\\n\\nThe following strings will be added to the end of this file\\n[mysqld]\\nserver-id = 1\\nlog_bin = /var/log/mysql/mysql-bin.log\\nmax_binlog_size = 100M\\nbinlog_format=ROW\\n\\nAfter that, MySQL Server will be restarted. The old version of the file will be saved under the name /etc/mysql/my.cnf.old\\n\\nDo you want to continue? [Y/n] "', 
  'CORRECT_BIN_LOG_SETTINGS': '"The binary log settings have adjusted correctly."', 
  'FAILED_RESTART_MYSQL': '"MySQL server has not been restarted"', 
  'WRONG_BACKUP_UTIL': '"Wrong backup util"', 
  'FAILED_CHANGE_BACKUP_UTIL': '"You can not change backup util"', 
  'LEAD_TO_THE_SITE_AFTER_CONNECTION': '"\\nTo create a backup job, click the \'Add new Job\' button at https://sqlbak.com/dashboard"', 
  'INCORRECT_PORT_SCOPE': '"The port number {0} is out of the allowed port\'s scope - {1}"', 
  'FAILED_GET_DBMS_NAME_BY_TYPE': '"Failed to get DBMS name by a type."', 
  'FAILD_RUN_JOB_BY_NAME_NO_ANY_JOBS': '"No backup jobs found. Please create at least one job https://sqlbak.com/dashboard"', 
  'FAILD_RUN_JOB_BY_NAME_NO_FOUND': '\'The "{0}" job cannot be found. Exists job: {1}\'', 
  'FAILD_RUN_JOB_BY_NAME_NEED_NAME': '\'Several jobs were found. Please choose the one you need. For example: sqlbak --run-job --job-name="{0}" Exists job: {1}\'', 
  'FAILD_RUN_JOB_BY_NAME_MORE_ONE_JOB_WITH_NAME': '\'Several jobs with the following names "{0}" were found\'', 
  'NO_INFO_PREVIOS_BACKUP': '"There is no information about the previous backup"', 
  'NO_INFO_PREVIOS_BINLOG': '"There is no information about the previous binlog"', 
  'PREVIOS_BACKUP_FAILED': '"The previous backup failed"', 
  'BINLOG_INDEX_NOT_FOUND': '"Path to binlog index file could not be found"', 
  'BINLOG_INDEX_NOT_PATH_FOUND': '\'Path to binlog index file could not be found: "{0}".\'', 
  'BINLOG_INDEX_NOT_PATH_FOUND_REMOUTE': '\'Path to binlog index file could not be found: "{0}". Please ensure that you are connecting to a local MySQL server, as this feature is not available for remote servers\'', 
  'LAST_BINLOG_NOT_FOUND': '"The name of the last binlog file could not be found"', 
  'LAST_BACKEDUP_BINLOG_NOT_FOUND': '"The last backed up binlog could not be found: {0}"', 
  'LAST_BINLOG_DONT_EXIST': '"The file of the latest backed up binlog does not exist or cannot be accessed"', 
  'BINLOG_FILE_NOT_FOUND': '"Binlog file {0} does not exist or is not available"', 
  'NEW_BINLOG_FILE_NOT_FOUND': '"No new binarry log files found"'}, 
 'ru':{}}

# okay decompiling /home/lm/PycharmProjects/backs/pyc/sqlbak/app_output.pyc
