from sqlbak.definitions import REQUEST_PATH_CONSTS
CONSOLE_COMMANDS = [
 {'command':"--start", 
  'short_command':"-s", 
  'local_rest_settings':{'is_get_method':False, 
   'url':REQUEST_PATH_CONSTS["runApp"]}, 
  'description':"run the SqlBak application's service", 
  'is_public':False},
 {'command':"--register", 
  'short_command':"-r", 
  'params':{'required':[
    {'name':{"key": "k"}, 
     'description':"the secret key from https://sqlbak.com/download (you must be logged in to see the key).",  'is_public':True}], 
   'optional':[
    {'name':{"name": "n"}, 
     'value':None,  'description':"this server name (if omitted, the current server name is taken)",  'is_public':True},
    {'name':{"mysqldump-path": "md"}, 
     'value':None,  'description':"the path to mysqldump (default: /usr/bin/mysqldump)",  'is_public':True},
    {'name':{"mysql-path": "ms"}, 
     'value':None,  'description':"the path to mysql (default: /usr/bin/mysql)",  'is_public':True},
    {'name':{"mysql-binlog-base-path": "mbbp"}, 
     'value':None,  'description':"the path to a binlog directory (default: SHOW VARIABLES LIKE 'log_bin_basename')",  'is_public':True},
    {'name':{"mysql-binlog-index-path": "mbip"}, 
     'value':None,  'description':"the path to a binlog index file (default: SHOW VARIABLES LIKE 'log_bin_index')",  'is_public':True},
    {'name':{"pgdump-path": "pd"}, 
     'value':None,  'description':"the path to pg_dump (default: /usr/bin/pg_dump)",  'is_public':True},
    {'name':{"psql-path": "ps"}, 
     'value':None,  'description':"the path to psql (default: /usr/bin/psql)",  'is_public':True},
    {'name':{"sqlcmd-path": "sq"}, 
     'value':None,  'description':"the path to sqlcmd (default: /opt/mssql-tools/bin/sqlcmd)",  'is_public':True},
    {'name':{"mssql-data": "sqd"}, 
     'value':None,  'description':"the path to mssql's data directory (default: /var/opt/mssql/data/)",  'is_public':True},
    {'name':{"xtrabackup-path": "xb"}, 
     'value':None,  'description':"the path to xtrabackup (default: /usr/bin/xtrabackup)",  'is_public':False},
    {'name':{"mysql-lib": "ml"}, 
     'value':None,  'description':"the path to mysql lib (default: /var/lib/mysql/)",  'is_public':True},
    {'name':{"mongo-path": "mg"}, 
     'value':None,  'description':"the path to mongo util (default: /usr/bin/mongo)",  'is_public':True},
    {'name':{"mongodump-path": "mgd"}, 
     'value':None,  'description':"the path to mongodump util (default: /usr/bin/mongodump)",  'is_public':True},
    {'name':{"mongorestore-path": "mgr"}, 
     'value':None,  'description':"the path to mongorestore util (default: /usr/bin/mongorestore)",  'is_public':True},
    {'name':{"pg_restore-path": "pr"}, 
     'value':None,  'description':"the path to pg_restore util (default: /usr/bin/pg_restore)",  'is_public':True},
    {'name':{"sqlpackage-path": "spp"}, 
     'value':None,  'description':"the path to sqlpackage util (default: /var/opt/mssql-tools/sqlpackage/sqlpackage)",  'is_public':True},
    {'name':{"skip-interactive-add-connection": "siac"}, 
     'value':None,  'description':"",  'is_public':False}]}, 
  'local_rest_settings':{'is_get_method':False, 
   'url':REQUEST_PATH_CONSTS["registerAgent"]}, 
  'description':"register this server in SqlBak.com", 
  'is_public':True},
 {'command':"--update-settings", 
  'short_command':"-us", 
  'params':{"optional": [
                {'name':{"name": "n"}, 
                 'value':None,  'description':"this server name (if omitted, the current server name is taken)",  'is_public':True},
                {'name':{"mysqldump-path": "md"}, 
                 'value':None,  'description':"the path to mysqldump (default: /usr/bin/mysqldump)",  'is_public':True},
                {'name':{"mysql-path": "ms"}, 
                 'value':None,  'description':"the path to mysql (default: /usr/bin/mysql)",  'is_public':True},
                {'name':{"mysql-binlog-base-path": "mbbp"}, 
                 'value':None,  'description':"the path to a binlog directory (default: SHOW VARIABLES LIKE 'log_bin_basename')",  'is_public':True},
                {'name':{"mysql-binlog-index-path": "mbip"}, 
                 'value':None,  'description':"the path to a binlog index file (default: SHOW VARIABLES LIKE 'log_bin_index')",  'is_public':True},
                {'name':{"pgdump-path": "pd"}, 
                 'value':None,  'description':"the path to pg_dump (default: /usr/bin/pg_dump)",  'is_public':True},
                {'name':{"psql-path": "ps"}, 
                 'value':None,  'description':"the path to psql (default: /usr/bin/psql)",  'is_public':True},
                {'name':{"sqlcmd-path": "sq"}, 
                 'value':None,  'description':"the path to sqlcmd (default: /opt/mssql-tools/bin/sqlcmd)",  'is_public':True},
                {'name':{"mssql-data": "sqd"}, 
                 'value':None,  'description':"the path to mssql's data directory (default: /var/opt/mssql/data/)",  'is_public':True},
                {'name':{"xtrabackup-path": "xb"}, 
                 'value':None,  'description':"the path to xtrabackup (default: /usr/bin/xtrabackup)",  'is_public':False},
                {'name':{"mysql-lib": "ml"}, 
                 'value':None,  'description':"the path to mysql lib (default: /var/lib/mysql/)",  'is_public':True},
                {'name':{"mongo-path": "mg"}, 
                 'value':None,  'description':"the path to mongo util (default: /usr/bin/mongo)",  'is_public':True},
                {'name':{"mongodump-path": "mgd"}, 
                 'value':None,  'description':"the path to mongodump util (default: /usr/bin/mongodump)",  'is_public':True},
                {'name':{"mongorestore-path": "mgr"}, 
                 'value':None,  'description':"the path to mongorestore util (default: /usr/bin/mongorestore)",  'is_public':True},
                {'name':{"pg_restore-path": "pr"}, 
                 'value':None,  'description':"the path to pg_restore util (default: /usr/bin/pg_restore)",  'is_public':True},
                {'name':{"sqlpackage-path": "spp"}, 
                 'value':None,  'description':"the path to sqlpackage util (default: /var/opt/mssql-tools/sqlpackage/sqlpackage)",  'is_public':True}]}, 
  'local_rest_settings':{'is_get_method':False, 
   'url':REQUEST_PATH_CONSTS["updateAgent"]}, 
  'description':"update the server name and/or DBMS paths", 
  'is_public':True},
 {'command':"--unregister", 
  'short_command':"-u", 
  'local_rest_settings':{'is_get_method':False, 
   'url':REQUEST_PATH_CONSTS["setAgentActivity"]}, 
  'description':"unregister this server from SqlBak.com", 
  'is_public':True},
 {'command':"--add-connection", 
  'short_command':"-ac", 
  'params':{'required':[
    {'name':{"db-type": "dt"}, 
     'description':"the type of DBMS, can be 'mysql', 'postgresql', 'mssql', 'azure' or 'mongo'",  'is_public':True}], 
   'optional':[
    {'name':{"user": "u"}, 
     'value':"",  'description':"DBMS user name",  'is_public':True},
    {'name':{"connection-type": "ct"}, 
     'value':"tcp/ip",  'description':"DBMS connection type, supported values: tcp/ip",  'is_public':True},
    {'name':{"host": "h"}, 
     'value':"localhost",  'description':"DBMS host name, default: localhost",  'is_public':True},
    {'name':{"port": "P"}, 
     'value':None,  'description':"DBMS port, default: 3306 for MySQL, 5432 for PostgreSQL, 1433 for MSSQL, 27017 for MongoDB",  'is_public':True},
    {'name':{"password": "p"}, 
     'value':None,  'description':"DBMS user password",  'is_public':True},
    {'name':{"backup-util": "bu"}, 
     'value':"mysqldump",  'description':"Select the command-line utility to create a MySQL backup: mysqldump or xtrabackup. By default: mysqldump",  'is_public':True},
    {'name':{"use-ssh": "ssh"}, 
     'value':"n",  'description':"use SSH tunnelling, can be Y or N, default is N",  'is_public':True},
    {'name':{"ssh-port": "sshp"}, 
     'value':22,  'description':"ssh port number, default: 22",  'is_public':True},
    {'name':{"ssh-local-mapped-port": "sshmp"}, 
     'value':3306,  'description':"the local mapped port for ssh tunnel, default: 3306",  'is_public':True},
    {'name':{"database": "d"}, 
     'value':None,  'description':"Database, default: postgres for PostgreSQL, master for MSSQL, admin for MongoDB",  'is_public':True}], 
   'conditional':[
    {'name':{"ssh-host": "sshh"}, 
     'description':"ssh host name, required if --use-ssh=Y [-ssh Y]",  'is_public':True},
    {'name':{"ssh-user": "sshu"}, 
     'description':"ssh user name, required if --use-ssh=Y [-ssh Y]",  'is_public':True},
    {'name':{"ssh-password": "sshup"}, 
     'description':"ssh password, if not specified and --use-ssh=Y [-ssh Y] the app will ask it",  'is_public':True}]}, 
  'local_rest_settings':{'is_get_method':False, 
   'url':REQUEST_PATH_CONSTS["saveDBMSConnection"]}, 
  'description':"add new DBMS connection", 
  'is_public':True},
 {'command':"--update-connection", 
  'short_command':"-uc", 
  'params':{'required':[
    {'name':{"connection-id": "ci"}, 
     'description':"an id of the DBMS connection",  'is_public':True}], 
   'optional':[
    {'name':{"db-type": "dt"}, 
     'value':None,  'description':"the type of DBMS, can be 'mysql', 'postgresql', 'mssql', 'azure' or 'mongo'",  'is_public':True},
    {'name':{"connection-type": "ct"}, 
     'value':None,  'description':"DBMS connection type, supported values: tcp/ip",  'is_public':True},
    {'name':{"host": "h"}, 
     'value':None,  'description':"DBMS host name",  'is_public':True},
    {'name':{"port": "P"}, 
     'value':None,  'description':"DBMS port",  'is_public':True},
    {'name':{"user": "u"}, 
     'value':None,  'description':"DBMS user name",  'is_public':True},
    {'name':{"password": "p"}, 
     'value':None,  'description':"DBMS user password",  'is_public':True},
    {'name':{"backup-util": "bu"}, 
     'value':"mysqldump",  'description':"Select the command-line utility to create a MySQL backup: mysqldump or xtrabackup. By default: mysqldump",  'is_public':True},
    {'name':{"use-ssh": "ssh"}, 
     'value':None,  'description':"use SSH tunnelling, can be Y or N",  'is_public':True},
    {'name':{"ssh-host": "sshh"}, 
     'value':None,  'description':"ssh host name, required if --use-ssh=Y",  'is_public':True},
    {'name':{"ssh-user": "sshu"}, 
     'value':None,  'description':"ssh user name, required if --use-ssh=Y",  'is_public':True},
    {'name':{"ssh-password": "sshup"}, 
     'value':None,  'description':"ssh password",  'is_public':True},
    {'name':{"ssh-port": "sshp"}, 
     'value':None,  'description':"ssh port number",  'is_public':True},
    {'name':{"ssh-local-mapped-port": "sshmp"}, 
     'value':None,  'description':"the local mapped port for ssh tunnel",  'is_public':True},
    {'name':{"database": "d"}, 
     'value':None,  'description':"Database, default: postgres for PostgreSQL, master for MSSQL, admin for MongoDB",  'is_public':True}], 
   'conditional':[
    {'name':{"ssh-host": "sshh"}, 
     'description':"ssh host name, required if --use-ssh=Y",  'is_public':True},
    {'name':{"ssh-user": "sshu"}, 
     'description':"ssh user name, required if --use-ssh=Y",  'is_public':True},
    {'name':{"ssh-password": "sshup"}, 
     'description':"ssh password",  'is_public':True}]}, 
  'local_rest_settings':{'is_get_method':False, 
   'url':REQUEST_PATH_CONSTS["updateAgentConnection"]}, 
  'description':"update a DBMS connection", 
  'is_public':True},
 {'command':"--show-connection", 
  'short_command':"-sc", 
  'params':{"optional": [
                {'name':{"connection-id": "ci"}, 
                 'value':None,  'description':"an id of the DBMS connection",  'is_public':True},
                {'name':{"db-type": "dt"}, 
                 'value':"all",  'description':"DBMS type, can be 'mysql', 'postgresql', 'mssql' or 'all' (which is default)",  'is_public':True}]}, 
  'local_rest_settings':{'is_get_method':False, 
   'url':REQUEST_PATH_CONSTS["getAgentConnection"]}, 
  'description':"show DBMS connection settings", 
  'is_public':True},
 {'command':"--test-connection", 
  'short_command':"-tc", 
  'params':{"required": [{'name':{"connection-id": "ci"},  'description':"an id of the DBMS connection",  'is_public':True}]}, 
  'local_rest_settings':{'is_get_method':False, 
   'url':REQUEST_PATH_CONSTS["testAgentConnection"]}, 
  'description':"test a DBMS connection", 
  'is_public':True},
 {'command':"--remove-connection", 
  'short_command':"-rc", 
  'params':{"required": [{'name':{"connection-id": "ci"},  'description':"an id of the DBMS connection",  'is_public':True}]}, 
  'local_rest_settings':{'is_get_method':False, 
   'url':REQUEST_PATH_CONSTS["removeAgentConnection"]}, 
  'description':"delete a DBMS connection", 
  'is_public':True},
 {'command':"--jobs", 
  'short_command':"-j", 
  'params':{"optional": [
                {'name':{"--text-only": "to"}, 
                 'value':None,  'description':"Set this to yes for disable formatting",  'is_public':False}]}, 
  'local_rest_settings':{'is_get_method':False, 
   'url':REQUEST_PATH_CONSTS["listJobs"]}, 
  'description':"list all jobs", 
  'is_public':True},
 {'command':"--run-job", 
  'short_command':"-rj", 
  'params':{"optional": [
                {'name':{"job-id": "ji"}, 
                 'value':None,  'description':"the job id",  'is_public':True},
                {'name':{"job-name": "jn"}, 
                 'value':None,  'description':"the job name",  'is_public':True},
                {'name':{"backup-type": "bt"}, 
                 'value':"Full",  'description':"the backup type (Full/Diff/Inc)",  'is_public':True}]}, 
  'local_rest_settings':{'is_get_method':False, 
   'url':REQUEST_PATH_CONSTS["runJob"]}, 
  'description':"run a job", 
  'is_public':True},
 {'command':"--help", 
  'short_command':"-h", 
  'params':{"optional": [{'name':{"command": "c"},  'value':"all",  'description':"command name (full or short name without dashes)",  'is_public':True}]}, 
  'local_rest_settings':{'is_get_method':False, 
   'url':REQUEST_PATH_CONSTS["showConsoleCommands"]}, 
  'description':"list all possible commands or usage of a specific command", 
  'is_public':True},
 {'command':"--version", 
  'short_command':"-v", 
  'local_rest_settings':{'is_get_method':True, 
   'url':REQUEST_PATH_CONSTS["getAppVersion"]}, 
  'description':"get the application version", 
  'is_public':True},
 {'command':"--set-logs", 
  'short_command':"-sl", 
  'params':{"optional": [{'name':{"activate": "a"},  'value':"Y",  'description':"activate logging, cab be Y or N, default is Y",  'is_public':True}]}, 
  'local_rest_settings':{'is_get_method':True, 
   'url':REQUEST_PATH_CONSTS["setAppLogs"]}, 
  'description':"enable or disable the advanced logging", 
  'is_public':True},
 {'command':"--upload-logs", 
  'short_command':"-ul", 
  'local_rest_settings':{'is_get_method':True, 
   'url':REQUEST_PATH_CONSTS["uploadLogs"]}, 
  'description':"send the logs to the support team", 
  'is_public':True},
 {'command':"--info", 
  'short_command':"-i", 
  'local_rest_settings':{'is_get_method':True, 
   'url':REQUEST_PATH_CONSTS["getInfo"]}, 
  'description':"get the information about SqlBak app", 
  'is_public':True},
 {'command':"--update", 
  'short_command':"-up", 
  'local_rest_settings':{'is_get_method':True, 
   'url':REQUEST_PATH_CONSTS["updateApp"]}, 
  'description':"update the app", 
  'is_public':False},
 {'command':"--restart-service", 
  'short_command':"-rs", 
  'local_rest_settings':{'is_get_method':True, 
   'url':REQUEST_PATH_CONSTS["restartService"]}, 
  'description':"restart the service", 
  'is_public':False},
 {'command':"--upload_db", 
  'short_command':"-ud", 
  'local_rest_settings':{'is_get_method':True, 
   'url':REQUEST_PATH_CONSTS["uploadDb"]}, 
  'description':"upload the local db", 
  'is_public':False},
 {'command':"--stop", 
  'short_command':"-ss", 
  'local_rest_settings':{'is_get_method':True, 
   'url':REQUEST_PATH_CONSTS["stopService"]}, 
  'description':"stop the service", 
  'is_public':False},
 {'command':"--configure-mysql", 
  'short_command':"-cm", 
  'params':{"required": [{'name':{"connection-id": "ci"},  'description':"the connection id",  'is_public':True}]}, 
  'local_rest_settings':{'is_get_method':True, 
   'url':REQUEST_PATH_CONSTS["configureMysql"]}, 
  'description':"configure MySQL options to set up bin logs", 
  'is_public':True},
 {'command':"--check-ready-to-start", 
  'short_command':"-crs", 
  'local_rest_settings':{'is_get_method':True, 
   'url':REQUEST_PATH_CONSTS["checkReadyToStart"]}, 
  'description':"Checking that the application is connected to sqlbak.com and at least one connection is configured", 
  'is_public':False},
 {'command':"--run-job-collector", 
  'short_command':"-rjc", 
  'local_rest_settings':{'is_get_method':True, 
   'url':REQUEST_PATH_CONSTS["runJobCollector"]}, 
  'description':"Run job process collector", 
  'is_public':False},
 {'command':"--run-subservice", 
  'short_command':"-rss", 
  'params':{"required": [{'name':{"service-name": "sn"},  'description':"Name of internal service",  'is_public':False}]}, 
  'local_rest_settings':{'is_get_method':True, 
   'url':REQUEST_PATH_CONSTS["runSubservice"]}, 
  'description':"Run internal app subservice", 
  'is_public':False},
 {'command':"--menu", 
  'short_command':"-m", 
  'local_rest_settings':{'is_get_method':True, 
   'url':REQUEST_PATH_CONSTS["interactiveMenu"]}, 
  'description':"Open interactive menu", 
  'is_public':True}]

# okay decompiling /home/lm/PycharmProjects/backs/pyc/sqlbak/console_commands.pyc
