
LOG_ACTIONS = {'en':{
  'Dst_AbortUploadFileError2': '\'Failed to abort file upload "%(File)s": %(Error)s\'', 
  'Job_CompressFolderBackup3': '\'Compressing "%(Path)s" folder with %(ArchiveEngine)s archiver. Encryption: "%(ArchiveEncryption)s"\'', 
  'Job_CompressFolderBackup2': '\'Compressing "%(Path)s" folder with %(ArchiveEngine)s archiver\'', 
  'Job_CompressFolderBackup4': '\'Compressing "%(Path)s" folder with %(ArchiveEngine)s archiver. Encryption: "%(ArchiveEncryption)s". Password: "%(ArchivePassword)s"\'', 
  'Dst_GetFile2': '\'Getting "%(RemoteFile)s" file metadata on "%(RemoteFolder)s" folder\'', 
  'Cln_CleanupJob1': '\'Cleaning up backups of "%(JobName)s" job\'', 
  'Dst_AttemptFailed1': '"Destination error: %(Error)s"', 
  'Job_SqlScriptOut2': '"SQL script has finished successfully. %(Text)s"', 
  'Dst_SendToDestinationError3': '\'%(Destination)s destination "%(Configuration)s" error: %(Error)s\'', 
  'Job_ForcedUpdate': '"The important updates are available. The application will be updated automatically soon."', 
  'Job_SendToBadEmailError2': '\'The email can not be sent to "%(EmailAddresses)s". "%(Error)s"\'', 
  'Job_MaintenanceCliStart4': '\'Starting maintenance job by CLI "%(JobName)s" - "%(BackupType)s". Server "%(ClientName)s". Account "%(UserFullName)s". App v."%(ClientVersion)s".\'', 
  'SqlBak_DestinationCleanupError4': '\'Failed to clean up %(Destination)s destination "%(Configuration)s": %(Error)s\'', 
  'SBF_SendEmailError': '"Can not send email to %(EmailAddresses)s: %(Error)s"', 
  'Job_RestoreLastObjectNotFoundError': '"Object %(SourceDatabase)s not found on the destination"', 
  'Job_SubscriptionExpiredBefore7Warning': '"The optional Full-Service subscription has expired. You will stop receiving backup notifications in %(Count)s days. ${%(Url)s|Renew the subscription} or configure your own mail server"', 
  'Job_ValidateEmailError1': '"Failed to validate emails. %(Error)s"', 
  'Sql_BacpacConsistentWarning': '\'For an export to be transactionally consistent, you must ensure either that no write activity is occurring during the export, or that you are exporting from a snapshot of your Azure SQL database. Turn on "Create database snapshot for backup" option at Backup options section for export to be transactionally consistent.\'', 
  'Job_UncompressedBackup1': '\'Uncompressing "%(Files)s" file with %(ArchiveEngine)s archiver. \'', 
  'Dst_GetFolderByPath1': '\'Reading folder information by path: "%(Folder)s"\'', 
  'Dst_SendFilesToDestination3': '\'Sending backup of "%(ObjectName)s" to %(Destination)s destination "%(Configuration)s"\'', 
  'Job_RunScriptAfterBackup1': '"Running %(Script)s script after backup"', 
  'Sql_VerifyDatabase1': '\'Verifying "%(Database)s" database backup\'', 
  'Sql_BackupDatabaseBacpac1': '\'Backing up "%(Database)s" database to .bacpac file\'', 
  'Job_StartError2': '\'Failed to run "%(JobName)s" job: %(Error)s\'', 
  'Dst_SetCurrentFolder1': '\'The current destination folder is "%(Folder)s"\'', 
  'Job_CliStart5': '\'Starting job by CLI "%(JobName)s" - "%(BackupType)s". Server "%(ClientName)s". Account "%(UserFullName)s". App v."%(ClientVersion)s".\'', 
  'Job_ScriptError2': '"%(Script)s script error: %(Error)s"', 
  'Job_CompressDatabaseBackup2': '\'Compressing "%(Backup)s" file with %(ArchiveEngine)s archiver\'', 
  'Job_CompressDatabaseBackup3': '\'Compressing "%(Backup)s" file with %(ArchiveEngine)s archiver. Encryption: "%(ArchiveEncryption)s"\'', 
  'Job_CompressDatabaseBackup4': '\'Compressing "%(Backup)s" file with %(ArchiveEngine)s archiver. Encryption: "%(ArchiveEncryption)s". Password: "%(ArchivePassword)s"\'', 
  'Cln_JobCleanupError2': '\'Failed to clean up backups of "%(JobName)s" job: %(Error)s\'', 
  'Job_RunMaintenanceScript1': '"Running %(Script)s maintenance script"', 
  'Cln_FolderType': '"folder"', 
  'Job_DeleteFileError2': '\'Failed to delete file "%(FilePath)s": %(Error)s\'', 
  'Dst_UploadingFileRest3': '\'Uploading the rest of "%(RemoteFile)s" file: "%(FileChunkLength)s"\'', 
  'Job_RestoreDatabaseByTriggerBackupNotFoundd5': '\'Can not restore "%(DestinationDatabase)s" database on "%(Computer)s" server.  "%(SourceDatabase)s" backup on "%(DestinationType)s: %(DestinationConfiguration)s" destination not found\'', 
  'SqlBak_DestinationError4': '"Destination error: %(Error)s"', 
  'Job_ScheduledStart4': '\'Starting scheduled job "%(JobName)s" - "%(BackupType)s". App v."%(ClientVersion)s"\'', 
  'Job_ScheduledStart5': '\'Starting scheduled job "%(JobName)s" - "%(BackupType)s". Server "%(ClientName)s". Account "%(UserFullName)s". App v."%(ClientVersion)s".\'', 
  'Job_ScheduledStart3': '\'Starting scheduled job "%(JobName)s" - "%(BackupType)s". App v."%(ClientVersion)s"\'', 
  'Sql_BackupDatabaseSql1': '\'Backing up "%(Database)s" database to .sql file\'', 
  'Sql_BackupDatabaseBak3': '\'Backing up "%(Database)s" database to .bak file. Backup type: "%(BackupType)s". Checksum: "%(EnableCheckSum)s"\'', 
  'Sql_BackupDatabaseBak1': '\'Backing up "%(Database)s" database to .bak file\'', 
  'Job_RemoteBackupAzureErrorMessage': '\'Cannot perform the local backup procedure. The connected server is detected as Azure SQL Database. Please open the job settings and select "Azure SQL Database" server type on "Connect to Server" dialog to backup Azure SQL Databases.\'', 
  'Dst_FileSearch1': '\'Searching files by mask "%(SearchMask)s"\'', 
  'Dst_FileSearch2': '\'Searching files in "%(Folder)s" folder by "%(SearchMask)s" mask\'', 
  'Job_BackupFolder2': '\'Backing up "%(Folder)s" folder to %(Path)s\'', 
  'Sql_BackupDatabaseBakDone2': '\'"%(Database)s" database backup successfully completed. Backup type: "%(BackupType)s"\'', 
  'SBF_SendToWebLog': '"Sending report to ${%(Url)s|Web Log} "', 
  'SqlBak_JobError2': '"Job execution error: %(Error)s"', 
  'SqlBak_JobError4': '\'Job execution error: %(Error)s Server name: "%(AgentName)s"\'', 
  'Dst_NewAttempt': '"Trying again..."', 
  'Job_ScheduledMaintenanceStart4': '\'Starting scheduled maintenance job "%(JobName)s". Server "%(ClientName)s". Account "%(UserFullName)s". App v."%(ClientVersion)s".\'', 
  'Dst_CloseConnection2': '\'Disconnecting from %(Destination)s destination "%(Configuration)s"\'', 
  'Dst_SendFilesToDestinationProgress': '"Uploaded %(ProgressUpload)s - (average speed = %(Speed)s)"', 
  'Job_SkipFolderBackup2': '\'Skipping "%(Folder)s" folder backup. Reason: %(Warning)s\'', 
  'Job_BackupTypeChanged3': '"Last %(FailedBackupType)s backup was not started. Running %(NewBackupType)s backup instead of %(OldBackupType)s backup."', 
  'Dst_DownloadFile2': '\'Downloading file "%(File)s" to "%(LocalFolder)s"\'', 
  'Job_ScriptDatabase': '"Scripting %(Database)s database"', 
  'Cln_DatabaseType': '"database"', 
  'Job_RestoreDatabaseByTriggerBackupFailed5': '\'Can not restore "%(DestinationDatabase)s" database on "%(Server)s" server.  "%(SourceDatabase)s" backup on "%(DestinationType)s: %(DestinationConfiguration)s" destination failed\'', 
  'Job_TrialExpired': '"Your Professional Trial license expires in %(Count)s day and will be converted to Free automatically. ${%(Url)s|Purchase a license} to continue with your backups uninterrupted."', 
  'Cln_FolderNotFound': '"%(Folder)s not found on the destination."', 
  'Job_BackupDatabaseError4': '\'Failed to backup "%(Database)s" database with "%(BackupType)s" backup type : %(Error)s\'', 
  'Job_BackupDatabaseError3': '\'Failed to backup "%(Database)s" database with "%(BackupType)s" backup type: %(Error)s\'', 
  'Job_SkipDatabaseBackup2': '\'Skipping "%(Database)s" database backup. Reason: %(Warning)s\'', 
  'Job_BackupDatabaseErrorEc4': '\'Failed to backup "%(Database)s" database with "%(BackupType)s" backup type: %(Error)s\'', 
  'Dst_CreateFolder1': '\'Creating folder "%(Folder)s"\'', 
  'Sql_DropSnapshotDatabase1': '\'Drop "%(SnapshotName)s"\'', 
  'Arch_XceedWarning1': '"Xceed archiver error: %(Error)s"', 
  'Arch_Zip7Warning1': '"7-zip error: %(Error)s"', 
  'Dst_VerifyFile2': '\'Verifying remote file "%(File)s" with local one "%(LocalFile)s"\'', 
  'Dst_UploadFileError2': '\'Failed to upload file "%(File)s": %(Error)s\'', 
  'Job_FailedRestoreItem': '"Failed to restore %(SourceDatabase)s database. %(Error)s "', 
  'Job_RestoreDatabaseByTrigger3': '\'Restoring "%(DestinationDatabase)s" database on "%(Computer)s" server from backup of "%(SourceDatabase)s" database\'', 
  'Job_RestoreDatabaseByFiles': '\'Restoring "%(DestinationDatabase)s" database from files: "%(Files)s" \'', 
  'Job_ConnectingToSqlServer3': '"Connecting to %(SqlServerType)s: %(SqlServerVersion)s. %(SqlServerName)s"', 
  'Job_RestoreDatabaseByDate3': '\'Restoring "%(DestinationDatabase)s" database on "%(Date)s" from backup of "%(SourceDatabase)s" database\'', 
  'Job_BackupDatabases0': '"Backing up databases"', 
  'Job_BackupDatabases2': '\'Backing up "%(SqlServerName)s" %(SqlServerType)s databases\'', 
  'Job_JobCancelled': '"The job is cancelled"', 
  'Job_Start5': '\'Starting job "%(JobName)s" - "%(BackupType)s". Server "%(ClientName)s". Account "%(UserFullName)s". App v."%(ClientVersion)s".\'', 
  'Job_Start4': '\'Starting job "%(JobName)s" - "%(BackupType)s". App v."%(ClientVersion)s"\'', 
  'Job_Start3': '\'Starting job "%(JobName)s" - "%(BackupType)s". App v."%(ClientVersion)s"\'', 
  'Job_Start2': '\'Starting job "%(JobName)s" - "%(BackupType)s"\'', 
  'Dst_GetFolder1': '\'Reading the folder information: "%(Folder)s"\'', 
  'Job_RunError1': '"Job execution error: %(Error)s"', 
  'Job_DeleteFolderError2': '\'Failed to delete folder "%(FolderPath)s": %(Error)s\'', 
  'Job_CompressDatabaseBackupCompleted2': '\'Backup of "%(Database)s" successfully compressed to "%(Volumes)s"\'', 
  'Job_TrialExpiredToday': '"Your Professional Trial license expires today and will be converted to Free automatically. ${%(Url)s|Purchase a license} to continue with your backups uninterrupted."', 
  'Job_MaintenanceStart4': '\'Starting maintenance job "%(JobName)s". Server "%(ClientName)s". Account "%(UserFullName)s". App v."%(ClientVersion)s".\'', 
  'Job_SubscriptionExpiredAfter7Warning': '"The optional Full-Service subscription has expired. ${%(Url)s|Renew the subscription} or configure your own mail server."', 
  'Job_RestoreObjectNotFoundError': '"Object %(SourceDatabase)s by %(Date)s not found on the destination"', 
  'Cln_FileNotFound': '"%(Files)s not found on the destination."', 
  'Job_SubscriptionFeature': '"%(Text)s"', 
  'Job_RestoreDatabasesByTrigger2': '\'Restoring databases on "%(Computer)s" server from "%(DestinationConfiguration)s" destination\'', 
  'Job_RestoreDatabasesByTrigger3': '\'Restoring databases on "%(Computer)s" server from "%(DestinationType)s: %(DestinationConfiguration)s" destination\'', 
  'Cln_SelectResult3': '\'Found "%(FoundCount)s" backups of "%(ObjectName)s". Old backups: "%(SelectCount)s"\'', 
  'Job_SelectTempFolder1': '\'The working folder of the job is "%(TempFolder)s"\'', 
  'Job_CompressFolderBackupCompleted2': '\'Backup of "%(Path)s" has been successfully compressed to "%(Volumes)s"\'', 
  'Job_LostError1': '"Job error: %(Error)s"', 
  'Job_JobCancelled1': '"Job cancelled. %(Message)s"', 
  'Job_FailedSendEmailError': '"Failed to send email message. Detail: %(Detail)s"', 
  'SqlBak_ScriptError3': '"%(Script)s script error: %(Error)s"', 
  'Dst_DeleteFile1': '\'Deleting file "%(File)s"\'', 
  'SqlBak_SendEmail': '"Sending job log to %(EmailAddresses)s"', 
  'SBF_SendEmail': '"Sending job log to %(EmailAddresses)s"', 
  'Job_JobWorkingFolders4': '\'The backup folder "%(BackupFolder)s" has "%(BackupDriveFreeSpace)s" free space. The temporary folder "%(TempFolder)s" has "%(TempDriveFreeSpace)s" free space\'', 
  'Job_JobWorkingFolders2': '\'The backup folder is "%(BackupFolder)s". The temporary folder is "%(TempFolder)s"\'', 
  'Job_LinuxJobWorkingFolders2': '\'The temporary folder "%(TempFolder)s" has "%(TempDriveFreeSpace)s" free space\'', 
  'Job_BackupFolders0': '"Backing up folders"', 
  'Dst_FailedValidateMd5': '"Hash sum file verification at the destination has failed: %(Error)s"', 
  'Cln_DeleteFile4': '\'Deleting old backup of "%(ObjectName)s". Backup type: "%(BackupType)s". Backup time: "%(BackupAt)s". Files: %(Files)s\'', 
  'Cln_DeleteFile3': '\'Deleting old backup of "%(ObjectName)s". Backup type: "%(BackupType)s". Backup time: "%(BackupAt)s"\'', 
  'Job_TraceFileMaxSize1': '\'The maximum file size: "%(Size)s"\'', 
  'Job_RestoreCancelError3': '\'The "%(Database)s" database was not restored on "%(Computer)s" server: %(Error)s\'', 
  'Dst_UploadFile2': '\'Uploading local "%(File)s" to remote "%(RemoteFile)s"\'', 
  'Dst_UploadFile3': '\'Uploading local "%(File)s" to remote "%(RemoteFile)s" in folder "%(RemoteFolder)s"\'', 
  'Job_GetFileMaxSize': '"Getting maximum file size..."', 
  'Job_ScriptDatabaseItems': '"Scripting %(DatabaseItemTypes)s of %(Database)s database"', 
  'Job_SubscriptionExpiredingWarning': '"The optional Full-Service subscription expires in %(Count)s days. You will stop receiving email notifications. ${%(Url)s|Renew the subscription} or configure your own mail server."', 
  'Cln_DestinationCleanupError3': '\'Failed to clean up %(Destination)s destination "%(Configuration)s": %(Error)s\'', 
  'Job_CancellingJob1': '\'Cancelling job "%(JobName)s"\'', 
  'Job_FullBackupNotFoundError': '"Full backup not found"', 
  'Dst_GetFileLength2': '\'Getting "%(RemoteFile)s" file size at "%(Configuration)s"...\'', 
  'Job_BackupFolderError3': '\'Failed to backup "%(Folder)s" folder in %(Path)s. %(Error)s\'', 
  'Job_BackupDatabaseComplete3': '\'Database "%(Database)s" successfully backed up to "%(Backup)s : %(Size)s"\'', 
  'Job_BackupDatabaseComplete2': '\'Database "%(Database)s" successfully backed up to "%(Backup)s"\'', 
  'Sql_VerifyDatabaseWarning1': '"Backup verify: %(Error)s"', 
  'Job_ScriptOutput3': '\'%(Script)s script has finished with "%(ExitCode)s" code. Text output: %(Output)s\'', 
  'Job_ScriptOutput2': '\'%(Script)s script has finished with "%(ExitCode)s" code.\'', 
  'Job_PrefetchDatabaseItems': '"Prefetching objects of %(Database)s database"', 
  'Dst_OpenConnection2': '\'Connecting to %(Destination)s destination "%(Configuration)s"\'', 
  'Job_BackupDatabaseByTools': '\'Backing up "%(SqlServerName)s" databases with %(BackupToolsName)s: %(BackupToolsVersion)s\'', 
  'Dst_PrintFileLength3': '\'"%(RemoteFile)s" file size is "%(FileLength)s"\'', 
  'Job_RestoreFilesNotFound': '"Files to restore not found "', 
  'Cln_CleanupDestination4': '\'Cleaning up backups of "%(ObjectName)s" %(ObjectType)s at %(Destination)s destination "%(Configuration)s"\'', 
  'Cln_CleanupDestination2': '\'Cleaning up backups at %(Destination)s destination "%(Configuration)s"\'', 
  'Job_FinishedWithErrors2': '\'Job "%(JobName)s" finished with "%(ErrorCount)s" errors\'', 
  'Job_FinishedWithErrors1': '\'Job "%(JobName)s" finished with errors\'', 
  'Dst_CleanupFolder1': '\'Cleaning up "%(Folder)s" folder\'', 
  'Cln_DestinationCleanupConfirmWarning3': '\'Unable to confirm cleaning up files "%(Configuration)s" %(Destination)s destination: %(Error)s\'', 
  'SqlBak_SendEmailError': '"Can not send email to %(EmailAddresses)s: %(Error)s"', 
  'Dst_AbortUploadFile1': '\'Aborting file upload "%(File)s"\'', 
  'Dst_DownloadFileError2': '\'Failed to download file "%(File)s": %(Error)s\'', 
  'Sql_CreateSnapshotDatabase1': '\'Creating snapshot of "%(Database)s" database to "%(SnapshotName)s"\'', 
  'Job_BackupDatabaseSkip1': '\'Skipping "%(Database)s" database backup\'', 
  'Dst_CreateFolderByPath1': '\'Creating folder by path "%(Folder)s"\'', 
  'Job_ChangeBackupType4': '\'The previous %(LastBackupType)s backup of "%(Database)s" database has failed. Creating %(BackupType)s backup.\'', 
  'Job_SubscriptionExpiredingTodayWarning': '"The optional Full-Service subscription expires today. You will stop receiving email notifications. ${%(Url)s|Renew the subscription} or configure your own mail server."', 
  'SBF_SendToWebLogError': '"Web log cannot be sent: %(Error)s. Will try to send later."', 
  'Job_DifferenceVersionsSynkError': '\'Can not read the current version of the backup job from sqlbak.com server. Detail: "%(Text)s".\'', 
  'Dst_FoundedFiles1': '\'Found "%(FoundCount)s" files.\'', 
  'Cln_CleanupPercent1': '"%(Percent)s% completed"', 
  'Job_RestoreDatabasesByTrigger': '"Restoring databases..."', 
  'Job_FinishedSuccessfully1': '\'Job "%(JobName)s" finished\'', 
  'Dst_ReopenConnection2': '\'Reconnecting to %(Destination)s destination "%(Configuration)s"\'', 
  'Job_RunScriptBeforeBackup1': '"Running %(Script)s script before backup"', 
  'Job_BrokenChainErrorMessage4': '\'[%(Code)s]. The previos %(LastBackupType)s backup of "%(Database)s" database was created with a different application. (not %(AppName)s). You may not able to restore the database automatically using %(AppName)s.\'', 
  'Job_BrokenChainWarningMessage4': '\'#[%(Code)s]. Previos %(LastBackupType} backup of "%(Database)s" database was created with a different application. (non %(AppName)s). You may not able to restore the database automatically using %(AppName)s. Skipping current backup.\'', 
  'Job_BrokenChainChangeBackupTypeMessage4': '\'#[%(Code)s]. Previos %(LastBackupType)s backup of "%(Database)s" database was create with a different application. (not %(AppName)s). Changing backup type to Full.\'', 
  'Job_DataSchemaChanged': '"The data schema has been changed. A full backup will be performed."', 
  'Job_ScriptAfterRestore1': '\'The result of executing the script that was launched after restoration:. "%(Message)s"\'', 
  'Job_ChangeBackupType2': '\'A "%(BackupType)s"\\u200b\\u200b\\u200b\\u200b\\u200b\\u200b\\u200b backup cannot be performed. A full backup will be performed. The reason is: "%(Error)s"\'', 
  'Job_ChangeBackupType3': '\'A "%(BackupType)s"\\u200b\\u200b\\u200b\\u200b\\u200b\\u200b\\u200b backup cannot be performed for "%(Database)s". A full backup will be performed. The reason is: "%(Error)s"\'', 
  'Sql_CreateSnapshotDatabase1': '\'Creating snapshot of "%(Database)s" database to "%(SnapshotName)s".\'', 
  'Sql_BackupDatabaseBacpac2': '\'Backing up "%(Database)s" database to "%(Ext)s" file.\'', 
  'Sql_BinLogBackuped2': '\'The backup includes a binlog file: "%(File)s". Size: "%(Size)s"\''}, 
 'ru':{}}


